### ISSUE TITLE
Add additional descriptor to distinguish local plugins (conflict with GitHub name)

### ISSUE THREAD

**Issue by gennaro-tedesco** [zap-zsh/zap#159]
### If the feature solves a problem you have, specify it here.

Currently the syntax to install a remote plugin is:
```bash
plug "<github-name>/repository-name"
```
which ideally automatically resolves to `ZAP_GIT_PREFIX` and pulls the corresponding code from the hosting service. Likewise, to install local plugins, as per the README

> A file descriptor which points to a directory is treated as a plugin, versus a regular file

```bash
# Example sourcing of local files
plug "$HOME/.config/zsh/aliases.zsh"
```
This mechanism however generates a conflict when, accidentally, the `<github-name>` corresponds to a folder name on the local machine, and it seems that in such a case Zap defaults to looking in the local directories and if nothing is found, the plugin is skipped or not activated (or whichever other exception mechanism is in place, I have not checked the code yet).

## Example

A classical example is when trying to install your own plugins hosted under your name. And sometimes the `$HOME` directory on your computer has the same name, thus bypassing the installation of the remote plugin.

## Question

How can one go around this? Ideally I would propose to add an additional qualifier to indicate that you are explicitly sourcing a local plugin, something along the lines of
```bash
plug "<name>/folder" "local=true"
```
or the like.

**Comment by wintermi** [comment]
You are correct, a check for a local directory is made before attempting to clone a Git repository.  If you were to execute the following command within a terminal window:

```
plug "zsh-plugin"
```

and there was a directory relative to your current path called "zsh-plugin", it will assume that you are attempting to load a local directory as a plugin.

Ideally an absolute local path should be provided, though in its current form it is not required.

There is however a quick fix that would resolve the immediate issue with relative directories being picked up instead of cloning a Git repository.

I would prefer to make this change before considering adding additional argument support to `plug`.  As if we were to add argument support, then I would prefer a larger design discussion be had.

**Comment by wintermi** [comment]
@gennaro-tedesco - Please update to version 1.2.1 and restart your terminal sessions.  If you experience the same issue please reopen.

**Comment by gennaro-tedesco** [comment]
I confirm it works with the latest commit, thank you for the quick effort!!

P. S.

> Please update to version 1.2.1

`zap version` only shows the latest commit, the version number is not included, is it?

**Comment by wintermi** [comment]
Please execute `zap update self` which will update your version of Zap that includes the version number.

You could also execute the following to perform a clean install of Zap and all your existing plugins:

```
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 --keep
```
