### ISSUE TITLE
feat: check if plugin needs to be updated

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#59]
show text next to plugin name indicating if it needs to be updated or if it's already up to date

**Comment by ChristianChiarulli** [comment]
`new version available`
`up to date`

**Comment by Pheon-Dev** [comment]
Like Mason

**Comment by AntPeixe** [comment]
I was wondering, what should be shown for the update?

Mason shows you the new release which makes sense since you are usually installing a whole library / framework / etc. However for plugins it's common that they aren't tagged at all. Should it just show the latest commit on master/main branch?

Also, what should be done for the plugins that are pinned? Should those be ignored for the update?
