### ISSUE TITLE
Plug not working for WSL2 Ubuntu 22.04

### ISSUE THREAD

**Issue by vunhatchuong123** [zap-zsh/zap#88]
This is my `.zshrc`
```bash
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

HISTFILE=~/.zsh_history

source "$ZDOTDIR/functions.zsh"

zshsource "exports"
zshsource "aliases"

# Example install plugins
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/zap-prompt"

# Manually source since zap plug doesnt work
source "$HOME/.local/share/zap/plugins/zap-prompt/zap-prompt.zsh-theme"
source "$HOME/.local/share/zap/plugins/supercharge/supercharge.plugin.zsh"
source "$HOME/.local/share/zap/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

zshsource "git"

zshsource "keymaps"
```

Everything in this file works except lines with `plug`.  `zshsource` does nothing special other than sourcing those files.

**Comment by mamaraddio** [comment]
It seams to work for me. Could you provide some other informations?
For example, what do you have inside `"$ZDOTDIR/functions.zsh"`, maybe something could conflict with zap?

![image](https://user-images.githubusercontent.com/82162277/210080036-a388b449-e025-475d-a2b2-be1a7435a3eb.png)

This is the `.zshrc` file created on the fly just to test this.
```sh
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/tux/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

plug "zap-zsh/supercharge"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/zap-prompt"
plug "zsh-users/zsh-syntax-highlighting"
```

P.S:
You don't need anymore your `zshsource` function because `plug` is able to source your local files
P.P.S:
You can even use plug as a command in your zsh session to source any file, obviously this does not persist to the next zsh reload

![image](https://user-images.githubusercontent.com/82162277/210081369-f6185420-3df3-4631-a205-8e8a4073a792.png)

**Comment by vunhatchuong123** [comment]
It looks like you are correct, my `zshsource` is the problem, weird that it works fine on my PopOS and EndeavorOS machine. All of them use the same setup.
Also the reason I don't want to use `plug` to source my files since I have to use `plug "$ZDOTDIR/alias.zsh"`, I can't omit the extension and location.

**Comment by mamaraddio** [comment]
Maybe I didn't fully understand, but you can pass to plug an argument wrapped with " (quotation marks) representing a file descriptor, so it can contains an variable (such as $ZDOTDIR) or files without extensions, if the file represented by $1 is a regular file, plug will source it. You could do, for exaple:
```sh
plug "$ZDOTDIR/aliases"
```
or even:
```sh
plug "${ZDOTDIR:-$HOME}/aliases"
```
that will defaults to `$HOME` if `$ZDOTDIR` is not set. (This is a Zsh feature, not zap)

**Comment by vunhatchuong123** [comment]
Omit `.zsh` does not work, it will try to clone home and fail then doesn't apply the file.
![image](https://user-images.githubusercontent.com/20581504/210094265-567e4ce2-cd83-4b67-b1d3-6e2b798e2bca.png)

Also, I want to omit `$ZDOTDIR` completely in `plug`, that's why I made a separate function. Maybe you can add one of the location  to `_try_source` is `$ZDOTDIR` ?

**Comment by mamaraddio** [comment]
In the case your file is named `aliases.zsh` you actually need the extension. `Plug` works like so:
- If the first argument describe a regular existing file, _plug_ will source it
- otherwise _plug_ try to `git clone` the plugin by splitting the argument at `/` and using the first field as the github username, and the last field as repo name

I think this issue can be closed because "**Plug not working on WSL2**" is not the point anymore.
You can always open a new "Feature request" for what you're looking for.

**Comment by mamaraddio** [comment]
I'm closing this because "the issue" is not related to `zap:plug` but is due to a user config
