### ISSUE TITLE
MacOS sed shows invalid command during installation

### ISSUE THREAD

**Issue by 0xleowang** [zap-zsh/zap#95]
`sed: 1: "/Users/xxx/.zshrc": invalid command code e`
On MacOS Ventura 13.0.1, I got the above error during installation. This seems caused by the inconsistent versions of `sed` in GNU and BSD. 
https://github.com/zap-zsh/zap/blob/8d3ca001ac583d19a4033a66cfa248be3599d708/install.sh#L18-L19
According to [here](https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code): 
> On the OSX version of sed, the -i option expects an extension argument ...

One potential solusion is to use `sed -i.bak`, which works on both situations, but this will generate a `.bak` backup file. Another potential solution is to use `perl` instead of `sed`.

I'm sorry that I have limited knowledge in shell programming. Not sure which solution is cleaner and more aligned with the style of Zap, so I'd love to hear your thoughts.

**Comment by mamaraddio** [comment]
Hi @0xleowang, you found a good solution for #91, as suggested by @ChristianChiarulli we should have to backup the user's original config, the solution you posted with `sed -i.back` is great because solves two problems:
- solve the bug you reported
- accomplish to backup the original `.zshrc` file

I'm going to fix it in a while, thank you

**Comment by 0xleowang** [comment]
Cheers @mamaraddio . Glad to hear it.
